Bump version to 3.0, check SRC and PKG dirs, build txz, add cleanup option

diff --git a/thunderbird.SlackBuild b/thunderbird.SlackBuild
--- a/thunderbird.SlackBuild
+++ b/thunderbird.SlackBuild
@@ -3,6 +3,9 @@
 # Slackware build script for Mozilla Thunderbird
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
 # Based on the original build script by Patrick Volkerding <volkerdi@slackware.com>
+#
+# This is not a source build script.  Rather, it builds a Slackware
+# package from the official binary tarball available from mozilla.org.
 
 . ../slack-package.conf
 
@@ -11,89 +14,104 @@ TMP=${TMP:-/tmp}
 
 
 NAME=thunderbird
-VERSION=2.0.0.23
+VERSION=3.0
 ARCH=i686
 LOCALE=bg
 BUILD=1
 KDE_PATH=/usr
 
+CWD=`pwd`
 TMP=${TMP:-/tmp}
+PKG=$TMP/package-$NAME
 
-PKG=$TMP/package-thunderbird
-
-if [ ! -d $TMP ]; then
-  mkdir -p $TMP
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
 fi
 
-rm -rf $PKG
+SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+   echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+   exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+
 mkdir -p $PKG/usr/lib
-( cd $PKG/usr/lib
-  echo "Extracting files..."
-  tar xzvf $CWD/$NAME-$VERSION.tar.gz
-  mv $NAME $NAME-$VERSION
-  ln -sf $NAME-$VERSION $NAME
-  cd $NAME-$VERSION
-  echo "Patching some files..."
-  cat $CWD/$NAME.diff | sed s/VERSION/$VERSION/ | patch thunderbird --backup --suffix=.orig
-  cat $CWD/$NAME-firefox.txt >> defaults/pref/mailnews.js )
+
+cd $PKG/usr/lib
+tar -jxvf $CWD/$NAME-$VERSION.tar.bz2
+mv $NAME $NAME-$VERSION
+ln -sf $NAME-$VERSION $NAME
+cd $NAME-$VERSION
+
+# Patching the distribution
+patch -p1 < $CWD/$NAME-$VERSION.diff || exit 1
+cat $CWD/$NAME-firefox.txt >> defaults/pref/mailnews.js 
+
 mkdir -p $PKG/usr/bin
 ( cd $PKG/usr/bin
-  ln -sf /usr/lib/$NAME-$VERSION/$NAME . )
+  ln -sf /usr/lib/$NAME-$VERSION/$NAME .
+)
 
-echo "*** Configuring environment..."
+# Creating environment integration items
+install -m 755 -d $PKG/usr/lib/mozilla/plugins
+
 install -m 755 -d $PKG/usr/share/applications
-install -m 644 $CWD/thunderbird.desktop $PKG/usr/share/applications/$NAME.desktop
-install -m 755 -d $PKG/$KDE_PATH/share/icons/hicolor/48x48
-install -m 644 $PKG/usr/lib/$NAME-$VERSION/icons/mozicon50.xpm \
-               $PKG/$KDE_PATH/share/icons/hicolor/48x48/$NAME.png
-install -m 755 -d $PKG/$KDE_PATH/share/icons/hicolor/32x32
-convert -scale 32x32 \
-        $PKG/usr/lib/$NAME-$VERSION/icons/mozicon50.xpm \
-        $PKG/$KDE_PATH/share/icons/hicolor/32x32/$NAME.png
-install -m 755 -d $PKG/$KDE_PATH/share/icons/hicolor/16x16
-convert $PKG/usr/lib/$NAME-$VERSION/icons/mozicon16.xpm \
-        $PKG/$KDE_PATH/share/icons/hicolor/16x16/$NAME.png
-install -m 755 -d $PKG/usr/share/pixmaps
-convert $PKG/usr/lib/$NAME-$VERSION/icons/mozicon50.xpm \
-        $PKG/usr/share/pixmaps/$NAME.png
-echo "*** Prepring package..."
-install -m 755 -d $PKG/usr/doc/${NAME}-${VERSION}${LOCALE}
-install -m 644 $PKG/usr/lib/$NAME-$VERSION/LICENSE.txt \
-               $PKG/usr/doc/${NAME}-${VERSION}${LOCALE}/COPYING
-install -m 644 $PKG/usr/lib/$NAME-$VERSION/README.txt \
-               $PKG/usr/doc/${NAME}-${VERSION}${LOCALE}/README
+install -m 644 $CWD/$NAME.desktop $PKG/usr/share/applications/$NAME.desktop
 
-mkdir $PKG/install
+install -m 755 -d $PKG/usr/share/icons/hicolor/48x48
+install -m 644 $PKG/usr/lib/$NAME-$VERSION/chrome/icons/default/default48.png \
+               $PKG/$KDE_PATH/share/icons/hicolor/48x48/$NAME.png
+install -m 755 -d $PKG/usr/share/icons/hicolor/32x32
+install -m 644 $PKG/usr/lib/$NAME-$VERSION/chrome/icons/default/default32.png \
+               $PKG/$KDE_PATH/share/icons/hicolor/32x32/$NAME.png
+install -m 755 -d $PKG/usr/share/icons/hicolor/16x16
+install -m 644 $PKG/usr/lib/$NAME-$VERSION/chrome/icons/default/default16.png \
+               $PKG/$KDE_PATH/share/icons/hicolor/16x16/$NAME.png
+
+install -m 755 -d $PKG/usr/share/pixmaps
+install -m 644 $PKG/usr/lib/$NAME-$VERSION/chrome/icons/default/default32.png \
+               $PKG/usr/share/pixmaps/$NAME.png
+
+bin_perms $PKG
+
+# Creating documentation
+install -m 755 -d $PKG/usr/doc/$NAME-$VERSION$LOCALE
+install -m 644 $PKG/usr/lib/$NAME-$VERSION/README.txt \
+               $PKG/usr/doc/$NAME-$VERSION$LOCALE/README
+install -m 644 $CWD/MPLLIC    $PKG/usr/doc/$NAME-$VERSION$LOCALE/COPYING
+
+# Preparing package
+install -m 755 -d $PKG/install
 install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
 install -m 644 $CWD/slack-required $PKG/install/slack-required
 install -m 644 $CWD/slack-suggests $PKG/install/slack-suggests
 
-install -m 755 -d $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}
-install -m 644 $CWD/slack-desc \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/slack-desc
-install -m 644 $CWD/slack-required \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/slack-required
-install -m 644 $CWD/slack-suggests \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/slack-suggests
-install -m 644 $CWD/$NAME.desktop \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/$NAME.desktop
-install -m 644 $CWD/$NAME.diff
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/$NAME.diff
-install -m 644 $CWD/$NAME-firefox.txt \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/$NAME-firefox.txt
-install -m 644 $CWD/$NAME.SlackBuild \
-               $PKG/usr/src/slackbuilds/$NAME-${VERSION}${LOCALE}/$NAME.SlackBuild
+# Build information
+SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION$LOCALE
+install -m 755 -d $SBDIR
+install -m 644 $CWD/slack-desc          $SBDIR/slack-desc
+install -m 644 $CWD/slack-required      $SBDIR/slack-required
+install -m 644 $CWD/slack-suggests      $SBDIR/slack-suggests
+install -m 644 $CWD/$NAME.desktop       $SBDIR/$NAME.desktop
+install -m 644 $CWD/$NAME-firefox.txt   $SBDIR/$NAME-firefox.txt
+install -m 644 $CWD/$NAME-$VERSION.diff $SBDIR/$NAME-$VERSION.diff
+install -m 644 $CWD/$NAME.SlackBuild    $SBDIR/$NAME.SlackBuild
 
-echo "*** Building package..."
+# Building package
 PKG_DIR=${PKG_DIR:-$TMP}
 cd $PKG
-makepkg -l y -c n $PKG_DIR/$NAME-$VERSION$LOCALE-$ARCH-$BUILD$MYIN.tgz
-( cd $PKG_DIR
-  cat $CWD/slack-desc > $NAME-$VERSION$LOCALE-$ARCH-$BUILD$MYIN.txt
-  md5sum $NAME-$VERSION$LOCALE-$ARCH-$BUILD$MYIN.tgz > $NAME-$VERSION$LOCALE-$ARCH-$BUILD$MYIN.tgz.md5)
+PKGNAME=$NAME-$VERSION$LOCALE-$ARCH-$BUILD$MYIN
+makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
+cat $CWD/slack-desc > $PKG_DIR/$PKGNAME.txt
+md5sum $PKG_DIR/$PKGNAME.txz > $PKG_DIR/$PKGNAME.txz.md5
 
-echo "*** Cleaning up..."
-rm -r $PKG
-
-echo "*** All done."
+# Clean up (optionally)
+if [ "$1" == "--cleanup" ]; then
+  rm -r $PKG
+fi
 
